apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-monitoring-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/barakvalzer/k8s-minikube-python-mysql-monitoring'
    targetRevision: HEAD
    path: k8s
    helm:
      valueFiles:
        - monitoring/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true